# Generated by Django 5.2.8 on 2025-12-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_plan_userplan_delete_usercredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
