# Generated by Django 5.2.8 on 2025-12-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0004_userplan_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='monthly_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplan',
            name='monthly_used',
            field=models.IntegerField(default=0),
        ),
    ]
