# Generated by Django 5.2.8 on 2025-12-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0005_plan_monthly_limit_userplan_monthly_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='monthly_limit',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='monthly_used',
        ),
    ]
